# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: supechicken/cros-image-eve:14268.67.0
    steps:
      - run:
          name: Setup `sudo` permission
          command: |
            echo 'chronos ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/chronos
            mv /usr/bin/sudo /usr/bin/sudo.elf

            cat \<<'EOF' > /usr/bin/sudo
            #!/bin/sh
            exec /usr/bin/sudo.elf -S "${@}"
            EOF

            chmod +x /usr/bin/sudo
      - run:
          name: Install Chromebrew
          command: su -l chronos -c 'curl -Ls git.io/vddgY | bash'
      - run:
          name: Test packages
          command: su -l chronos -c "curl -L https://raw.githubusercontent.com/supechicken/crew-package-updater/main/tools/test_pkg.rb | ruby"
      - run:
          name: Print test results
          command: |
            cat /tmp/test_result

            if grep 'Failed' /tmp/test_result; then
              exit 1
            fi
      - store_artifacts:
          path: /tmp/build
